### YamlMime:ManagedReference
items:
- uid: com.eyerunnman.gridsystem.Editor.GridEditorConfigDataSO
  commentId: T:com.eyerunnman.gridsystem.Editor.GridEditorConfigDataSO
  id: GridEditorConfigDataSO
  parent: com.eyerunnman.gridsystem.Editor
  children:
  - com.eyerunnman.gridsystem.Editor.GridEditorConfigDataSO.DebugTileObject
  - com.eyerunnman.gridsystem.Editor.GridEditorConfigDataSO.TileHeightSnap
  langs:
  - csharp
  - vb
  name: GridEditorConfigDataSO
  nameWithType: GridEditorConfigDataSO
  fullName: com.eyerunnman.gridsystem.Editor.GridEditorConfigDataSO
  type: Class
  source:
    id: GridEditorConfigDataSO
    path: ''
    startLine: 467
  assemblies:
  - cs.temp.dll
  namespace: com.eyerunnman.gridsystem.Editor
  syntax:
    content: 'public class GridEditorConfigDataSO : ScriptableObject'
    content.vb: >-
      Public Class GridEditorConfigDataSO
          Inherits ScriptableObject
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: com.eyerunnman.gridsystem.Editor.GridEditorConfigDataSO.DebugTileObject
  commentId: F:com.eyerunnman.gridsystem.Editor.GridEditorConfigDataSO.DebugTileObject
  id: DebugTileObject
  parent: com.eyerunnman.gridsystem.Editor.GridEditorConfigDataSO
  langs:
  - csharp
  - vb
  name: DebugTileObject
  nameWithType: GridEditorConfigDataSO.DebugTileObject
  fullName: com.eyerunnman.gridsystem.Editor.GridEditorConfigDataSO.DebugTileObject
  type: Field
  source:
    id: DebugTileObject
    path: ''
    startLine: 470
  assemblies:
  - cs.temp.dll
  namespace: com.eyerunnman.gridsystem.Editor
  syntax:
    content: public EditorGridTile DebugTileObject
    return:
      type: com.eyerunnman.gridsystem.Editor.EditorGridTile
    content.vb: Public DebugTileObject As EditorGridTile
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: com.eyerunnman.gridsystem.Editor.GridEditorConfigDataSO.TileHeightSnap
  commentId: F:com.eyerunnman.gridsystem.Editor.GridEditorConfigDataSO.TileHeightSnap
  id: TileHeightSnap
  parent: com.eyerunnman.gridsystem.Editor.GridEditorConfigDataSO
  langs:
  - csharp
  - vb
  name: TileHeightSnap
  nameWithType: GridEditorConfigDataSO.TileHeightSnap
  fullName: com.eyerunnman.gridsystem.Editor.GridEditorConfigDataSO.TileHeightSnap
  type: Field
  source:
    id: TileHeightSnap
    path: ''
    startLine: 472
  assemblies:
  - cs.temp.dll
  namespace: com.eyerunnman.gridsystem.Editor
  syntax:
    content: public float TileHeightSnap
    return:
      type: System.Single
    content.vb: Public TileHeightSnap As Single
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: com.eyerunnman.gridsystem.Editor
  commentId: N:com.eyerunnman.gridsystem.Editor
  name: com.eyerunnman.gridsystem.Editor
  nameWithType: com.eyerunnman.gridsystem.Editor
  fullName: com.eyerunnman.gridsystem.Editor
- uid: com.eyerunnman.gridsystem.Editor.EditorGridTile
  commentId: T:com.eyerunnman.gridsystem.Editor.EditorGridTile
  parent: com.eyerunnman.gridsystem.Editor
  name: EditorGridTile
  nameWithType: EditorGridTile
  fullName: com.eyerunnman.gridsystem.Editor.EditorGridTile
- uid: System.Single
  commentId: T:System.Single
  parent: System
  isExternal: true
  name: Single
  nameWithType: Single
  fullName: System.Single
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
